### ISSUE TITLE
VAT Exclusive Price Shown

### ISSUE THREAD

**Issue by graydon2212** [pufferfish-tech/octopus-agile-pi-prices#13]
Hi,

I'm new to all of this, so hope I'm not making a mistake here....

I noticed the price shown on my Inky pHAT is 10.7p, but the account page on my Octopus Agile says 11.25p.  I have looked at the data downloaded from the Octopus API (Area K) and it says the exclusive rate is 10.71p and the inclusive rate is 11.255p.

Then I took a look at store_prices.py - this is where I'm totally clueless - I'm a complete newbie...

The code seems to say it is printing the value including vat to the Inky pHAT??? Is this correct? 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by graydon2212** [comment]
![Screenshot 2020-11-02 at 10 22 02](https://user-images.githubusercontent.com/72817666/97857348-7c207800-1cf5-11eb-9409-6f8ce8d65971.png)
![Screenshot 2020-11-02 at 10 22 22](https://user-images.githubusercontent.com/72817666/97857365-85114980-1cf5-11eb-9478-d2f174c5f5b1.png)
![Screenshot 2020-11-02 at 10 22 58](https://user-images.githubusercontent.com/72817666/97857372-893d6700-1cf5-11eb-8b69-6e4db43794bc.png)

**Comment by pufferfish-tech** [comment]
Have you changed your code to "K" in the first line of store_prices.py? 
You would need to re-run store_prices.py (and probably also delete the sqlite database file (octoprice.sqlite) first too) for this to update for existing data. 
I think its an area issue not a vat issue as my area is showing 10.7p for 10am->10:30am :)

**Comment by graydon2212** [comment]
Ah!..that might explain it!... my area code K is exactly 5% different to the default area code!!  Thanks....

my brain = garbage in, garbage out
